apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-applications
  namespace: infra-tools
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/anastasiia-p-807/goit-argo.git
        revision: HEAD
        directories:
          - path: namespace/*
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/anastasiia-p-807/goit-argo.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
